spring:
  # application:
  #   name: "music-service"
  datasource:
    url: "jdbc:mysql://localhost:3306/inventoryNumber"
    username: Anush
    password: anush2618
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
springdoc-swagger-ui:
  path : /swagger-ui.html
springdoc: 
  api-docs :
    path : /api-docs
